# These are supported funding model platforms

github: MGalaCyber
patreon: # MGalaXd1274
open_collective: # Replace with a single Open Collective username
ko_fi: MGalaCyber1274
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
paypal: MGalaXd1274
custom: ['https://paypal.com/MGalaXd1274', 'https://discord.gg/VzGNhtmmfB', 'https://galacyber.xyz']
